parameters:
    datatable_configs:
        member:
            settings:
                header: false
                nb_element: 5
            columns:
                vote_label:
                    label: vote.title
                    path: vote
                    options:
                        template: common/vote/_detail.html.twig
                vote_members:
                    path: vote_members
                    options:
                        template: common/vote/_member.html.twig
        member_vote:
            settings:
                header: false
                nb_element: 10
            columns:
                vote_label:
                    label: toto
                    path: .
                    options:
                        template: common/vote/_result.html.twig
